name: Core
version: '1.0-SNAPSHOT'
main: me.arkallic.core.Core
api-version: '1.21'

commands:
  core:
    description: Core command
  rank:
    description: Rank system command
    permission: core.rank
  setrank:
    description: Set a players rank
    permission: core.rank
  home:
    description: Home command
    permission: core.home
  homes:
    description: List of homes
    permission: core.home
  sethome:
    description: Set your home
    permission: core.home
  deletehome:
    description: Delete your home
    permission: core.home
    aliases:
      - delhome
      - removehome
  maxhomes:
    permission: core.maxhomes
  balance:
    permission: core.balance
    aliases:
      - bal
  coins:
    permission: core.coins
  Economy:
    permission: core.economy
