package me.mrarcane.core.commands;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import static me.mrarcane.core.utils.ChatUtils.sendChat;
import static me.mrarcane.core.utils.PlayerUtils.adminMode;

/**
 * File generated by: MrArcane
 * 4/3/2018
 **/
public class AdminModeCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender s, Command cmd, String label, String[] args) {
        if (s instanceof Player) {
            Player p = (Player) s;
            if (args.length == 0) {
                adminMode(p);
                return true;
            }
        }
        sendChat(s, "&cYou must be a player to do this.");
        return false;
    }
}

