package me.mrarcane.core.commands;

import me.mrarcane.core.Main;
import me.mrarcane.core.utils.BroadcastUtils;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.ConfigurationSection;

import java.util.List;

import static me.mrarcane.core.utils.ChatUtils.sendChat;

/**
 * File generated by: MrArcane
 * 1/9/2018
 **/
public class AutoBroadcastCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        ConfigurationSection cfg = Main.getInstance().getConfig();
        List<String> mList = cfg.getStringList("Broadcast.Messages");
        if (args.length == 0) {
            sendChat(sender, "&cUsage: /autobroadcast <add/delete/list>");
            return true;

        } else if (args[0].equalsIgnoreCase("add")) {
            if (args.length == 1) {
                sendChat(sender, "&cUsage: /autobroadcast add <message>");
                return true;
            }
            String msg = "";
            for (int i = 1; i < args.length; i++) {
                msg = msg + " " + args[i];
            }
            mList.add(msg.trim());
            cfg.getConfigurationSection("Broadcast").set("Messages", mList);
            sendChat(sender, String.format("&aSuccess! created broadcast &7'&f%s&7'", msg.trim()));
            Main.getInstance().saveConfig();
            BroadcastUtils.restart(Main.getInstance());
            return true;

        } else if (args[0].equalsIgnoreCase("delete") || args[0].equalsIgnoreCase("del")) {
            if (args.length == 1) {
                sendChat(sender, "&cUsage: /autobroadcast <delete/del> <int>");
                return true;
            }
            int i =  Integer.parseInt(args[1]) - 1;
            if (mList.size() < 1) {
                sendChat(sender, "&cThere are no messages defined.");
                return true;
            }
            if (i > mList.size()) {
                sendChat(sender, "&cError! That broadcast doesn't exist.");
                return true;
            }
            sendChat(sender, String.format("&aSuccess! removed broadcast &7'&f%s&7'", mList.get(i)));
            mList.remove(mList.get(i));
            cfg.getConfigurationSection("Broadcast").set("Messages", mList);
            Main.getInstance().saveConfig();
            BroadcastUtils.restart(Main.getInstance());
            return true;
        } else if (args[0].equalsIgnoreCase("list")) {
            for (int i = 0; i < mList.size(); i++) {
                sendChat(sender, String.format("&7%s. &a%s", i  + 1, mList.get(i)));
            }
            return true;
        }
        sendChat(sender, "&cInvalid command.");
        sendChat(sender, "&cUsage: /autobroadcast add <message>");
        return false;
    }
}
