package me.mrarcane.core.commands;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import static me.mrarcane.core.listeners.AwayListener.addAfk;
import static me.mrarcane.core.listeners.AwayListener.rMap;
import static me.mrarcane.core.utils.ChatUtils.sendChat;

/**
 * File generated by: MrArcane
 * 2/20/2018
 **/
public class AwayCommand implements CommandExecutor {

    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            if (args.length == 0) {
                sendChat(sender, "&cUsage: /away <reason>");
                return true;
            }
            String msg = "";
            for (String arg : args) {
                msg = msg + " " + arg;
            }
            rMap.put(p, msg.trim());
            addAfk(p);
            return true;
        }
        return false;
    }
}
