package me.mrarcane.core.commands;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;

import static me.mrarcane.core.utils.ChatUtils.sendAlert;

/**
 * File generated by: MrArcane
 * 12/20/2017
 **/
public class BroadcastCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        //Player p = (Player) sender;
        String msg = "";
        for (int i = 0; i < args.length; i++) {
            msg = msg + args[i] + " ";
        }
        sendAlert(msg);
        return false;
    }
}
