package me.mrarcane.core.commands;

import me.mrarcane.core.Main;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import static me.mrarcane.core.Main.core;
import static me.mrarcane.core.utils.ChatUtils.sendChat;

/**
 * File generated by: MrArcane
 * 11/7/2017
 **/
public class CoreCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            if (args.length == 0) {
                sendChat(p, "Name: " + Main.getInstance().getName());
                sendChat(p, "Author: " + Main.getInstance().getDescription().getAuthors());
                sendChat(p, "Version: " + Main.getInstance().getDescription().getVersion());
                sendChat(p, "Website: " + Main.getInstance().getDescription().getWebsite());
                return true;
            }

            if (args[0].equalsIgnoreCase("reload") || args[0].equalsIgnoreCase("rl")) {
                if (!p.hasPermission("core.reload")) {
                    sendChat(p, "&cNo permission.");
                    return true;
                }
                Main.getInstance().reloadConfig();
                Main.getInstance().saveConfig();
                    sendChat(p, core + "&cReloaded config.");
                    return true;
                }
                sendChat(p, "&cIncorrect command, try again.");
        }
        return false;
    }
}
