package me.mrarcane.core.commands;

import me.mrarcane.core.Main;
import me.mrarcane.core.utils.DaySwitchUtils;
import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.entity.Player;
import org.bukkit.plugin.Plugin;

import java.util.HashMap;
import java.util.Map;

import static me.mrarcane.core.utils.ChatUtils.sendAlert;
import static me.mrarcane.core.utils.ChatUtils.sendChat;
import static me.mrarcane.core.utils.DaySwitchUtils.fail;
import static me.mrarcane.core.utils.DaySwitchUtils.resetVote;

/**
 * File generated by: MrArcane
 * 1/20/2018
 **/
@SuppressWarnings("MismatchedQueryAndUpdateOfCollection")
public class DayCommand implements CommandExecutor {
    public static int yes = 0;
    public static int no = 0;
    public static Map<Player, Boolean> user = new HashMap<>();
    public static Map<Plugin, Boolean> sMap = new HashMap<>();
    private static ConfigurationSection vSection = Main.getInstance().getConfig().getConfigurationSection("Day switch");
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            boolean perksEnabled = Main.getInstance().getConfig().getConfigurationSection("General").getBoolean("Perks");
            boolean s = sMap.get(Main.getInstance());
            if (!perksEnabled) {
                sendChat(p, "&cDonation perks are offline.");
                return true;
            }
            if (user.containsKey(p)) {
                sendChat(p, "&cSorry, you've already voted.");
                return true;
            }
            if (fail.containsKey(Main.getInstance())) {
                sendChat(p, "&cSorry, the vote failed! Try again the next night.");
                return true;
            }
            int count = Bukkit.getOnlinePlayers().size();
            if (count <= 1) {
                sendChat(p, "&cThere must be at least 2 players online.");
                return true;
            }
            if (args.length == 0) {
                if (!p.isSleeping()) {
                    sendChat(p, "&cYou must get in bed to start the vote!");
                    return true;
                }
                if (Main.getInstance().getServer().getWorld("world").getTime() <= 12200) {
                    sendChat(p, "&cIt must be night to perform this action.");
                    return true;
                }
                if (s) {
                    sendChat(p, "&cVote is already in progress.");
                    return true;
                }
                sMap.put(Main.getInstance(), true);
                DaySwitchUtils.startVote();
                yes++;
                Main.getInstance().saveConfig();
                user.put(p, true);
                sendAlert(String.format("&7%s &ahas started a vote to change it to day, &7type /day <yes/no> ", p.getName()));
                return true;
            }
            if (args[0].equalsIgnoreCase("reset") && p.hasPermission("core.admin")) {
                resetVote();
                sendChat(p, "&aVoting reset");
                return true;
            }
            if (args[0].equalsIgnoreCase("yes")) {
                if (!s) {
                    sendChat(p, "&cVote must be initiated first.");
                    return true;
                }
                user.put(p, true);
                sendChat(p, "&aYou have voted to switch to day.");
                yes++;
                Main.getInstance().saveConfig();
                sendAlert(String.format("&7%s &ahas voted to make it day time. &7[&a%s&7/&c%s&7]", p.getName(), String.valueOf(yes), String.valueOf(no)));
                return true;
            }
            if (args[0].equalsIgnoreCase("no")) {
                if (!s) {
                    sendChat(p, "&cVote must be initiated first.");
                    return true;
                }
                user.put(p, true);
                no++;
                Main.getInstance().saveConfig();
                sendChat(p, "&cYou have voted to keep it night.");
                sendAlert(String.format("&7%s &ahas voted to keep it night time. &7[&a%s&7/&c%s&7]", p.getName(), String.valueOf(yes), String.valueOf(no)));
                return true;
            }  else {
                sendChat(p, "&cIncorrect command, try again.");
            }
            return true;
        }
        return false;
    }
}
