package me.mrarcane.core.commands;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;

import static me.mrarcane.core.utils.ChatUtils.sendAlert;

/**
 * File generated by: MrArcane
 * 3/27/2018
 **/
public class DillyCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        sendAlert("&6Dilly Dilly!");
        return false;
    }
}
