package me.mrarcane.core.commands;

import me.mrarcane.core.Main;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.util.List;

import static me.mrarcane.core.utils.ChatUtils.sendChat;

/**
 * File generated by: MrArcane
 * 1/7/2018
 **/
public class LinksCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            List<String> l = Main.getInstance().getConfig().getStringList("Links");
            for (String s : l) {
                sendChat(p, String.valueOf(s));
            }
            return true;
        }
        return false;
    }
}
