package me.mrarcane.core.commands;

import me.mrarcane.core.Main;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;

import static me.mrarcane.core.utils.ChatUtils.sendAlert;

/**
 * File generated by: MrArcane
 * 2/5/2018
 **/
public class PerksCommand implements CommandExecutor {

    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        boolean perks = Main.getInstance().getConfig().getConfigurationSection("General").getBoolean("Perks");
        if (perks == true) {
            Main.getInstance().getConfig().getConfigurationSection("General").set("Perks", false);
            sendAlert("&aDonation perks are now disabled!");
            Main.getInstance().saveConfig();
            return true;
        }
        Main.getInstance().getConfig().getConfigurationSection("General").set("Perks", true);
        Main.getInstance().saveConfig();
        sendAlert("&aDonation perks are now active!");
        return false;
    }
}
