package me.mrarcane.core.commands;

import me.mrarcane.core.Main;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.util.List;

import static me.mrarcane.core.utils.ChatUtils.sendChat;

/**
 * File generated by: MrArcane
 * 1/16/2018
 **/
public class RulesCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            List<String> r = Main.getInstance().getConfig().getStringList("Rules");
            if (args.length == 0) {
                sendChat(p, "&eRules:");
                for (int i = 0; i < r.size(); i++) {
                    sendChat(p, (i + 1) + ".&a " + r.get(i));
                }
                return true;
            }
            if (args[0].equalsIgnoreCase("add") && p.hasPermission("core.rules.admin")) {
                if (args.length < 2) {
                    sendChat(p, "&cUsage: /rules add <rule>");
                    return true;
                }
                String rule = "";
                StringBuilder sb = new StringBuilder();
                for (int i = 1; i < args.length; i++) {
                   rule = String.valueOf(sb.append(args[i]).append(" "));
                }
                r.add(rule);
                Main.getInstance().getConfig().set("Rules", r);
                Main.getInstance().saveConfig();
                sendChat(p, String.format("Added rule '&7%s&f' successfully.", rule.trim()));
                return true;
            }
            if (args[0].equalsIgnoreCase("remove") && p.hasPermission("core.rules.admin")) {
                if (args.length < 2) {
                    sendChat(p, "&cUsage: /rules delete <int>");
                    return true;
                }
                int i = Integer.parseInt(args[1]) - 1;
                sendChat(p, "&2Removed rule successfully.");
                r.remove(i);
                Main.getInstance().getConfig().set("Rules", r);
                Main.getInstance().saveConfig();
                return true;
            }
            return true;
        }
        return false;
    }
}
