package me.mrarcane.core.commands;

import org.bukkit.GameMode;
import org.bukkit.Location;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.util.HashMap;
import java.util.Map;

import static me.mrarcane.core.utils.ChatUtils.sendChat;

/**
 * File generated by: MrArcane
 * 1/13/2018
 **/
public class SpectateCommand implements CommandExecutor {
    public static Map<Player, Location> l = new HashMap<>();
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            Location loc = p.getLocation();
            Boolean isSpectator = p.getGameMode().equals(GameMode.SPECTATOR);
            if (args.length == 0) {
                if (!isSpectator) {
                    l.put(p, loc);
                    p.setGameMode(GameMode.SPECTATOR);
                    sendChat(p, "Switched to spectator mode.");
                    return true;
                } else {
                    p.teleport(l.get(p));
                    p.setGameMode(GameMode.SURVIVAL);
                    sendChat(p, "Switched to survival mode.");
                    l.remove(p);
                }
                return true;
            }
            return false;
        }
        return true;
    }
}
