package me.mrarcane.core.commands;

import me.mrarcane.core.Main;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.file.FileConfiguration;

import java.util.List;

import static me.mrarcane.core.utils.ChatUtils.sendChat;

/**
 * File generated by: MrArcane
 * 3/10/2018
 **/
public class StaffCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        FileConfiguration cfg = Main.getInstance().getConfig();
        List<String> s = cfg.getConfigurationSection("General").getStringList("Staff");
        for (String line : s) {
            sendChat(sender, line);
        }
        return false;
    }
}
