package me.mrarcane.core.commands;

import me.mrarcane.core.Main;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import static me.mrarcane.core.utils.ChatUtils.sendChat;

/**
 * File generated by: MrArcane
 * 1/9/2018
 **/
public class VoteCommand implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (sender instanceof Player) {
            Player p = (Player) sender;
            sendChat(p, Main.getInstance().getConfig().getConfigurationSection("Vote").getString("Url"));
            return true;
        }
        return false;
    }
}
