package me.mrarcane.core.listeners;

import org.bukkit.Location;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.AsyncPlayerChatEvent;
import org.bukkit.event.player.PlayerMoveEvent;
import org.bukkit.event.player.PlayerQuitEvent;

import java.util.HashMap;

import static me.mrarcane.core.utils.ChatUtils.color;
import static me.mrarcane.core.utils.ChatUtils.sendAlert;
import static me.mrarcane.core.utils.PlayerUtils.getColor;
import static me.mrarcane.core.utils.PlayerUtils.timePlayer;

/**
 * File generated by: MrArcane
 * 2/20/2018
 **/
public class AwayListener implements Listener {

    public static HashMap<Player, String> rMap = new HashMap<>();
    private static HashMap<Player, Long> tMap = new HashMap<>();
    public static void addAfk(Player p) {
        tMap.put(p, System.currentTimeMillis());
        sendAlert(String.format("&7%s &eis now away.", p.getDisplayName()));
        p.setPlayerListName(color(String.format("&7[Away&7] %s", p.getDisplayName())));
    }
    private static void delAFK(Player p) {
        sendAlert(String.format("&7%s &eis back from: &7%s &eafter: &7%s", p.getDisplayName(), rMap.get(p), timePlayer(tMap.get(p))));
        getColor(p);
        rMap.remove(p);
        tMap.remove(p);
    }
    @EventHandler
    private void onMove(PlayerMoveEvent e) {
        Player p = e.getPlayer();
        Location from = e.getFrom();
        Location to = e.getTo();
        if (from.getBlockX() != to.getBlockX() || from.getBlockZ() != to.getBlockZ()) {
            if (rMap.containsKey(p)) {
                delAFK(p);
            }
        }
    }
    @EventHandler
    private void onChat(AsyncPlayerChatEvent e) {
        Player p = e.getPlayer();
        if (rMap.containsKey(p)) {
            delAFK(p);
        }
    }
    @EventHandler
    private void onQuit(PlayerQuitEvent e) {
        Player p = e.getPlayer();
        if (rMap.containsKey(p)) {
            delAFK(p);
        }
    }
}
