package me.mrarcane.core.listeners;

import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.AsyncPlayerChatEvent;

import static me.mrarcane.core.utils.PlayerUtils.getColor;

/**
 * File generated by: MrArcane
 * 12/17/2017
 **/
public class ChatListener implements Listener {

    @EventHandler
    private static void onChat(final AsyncPlayerChatEvent e) {
        Player p = e.getPlayer();
        getColor(p);
    }
}
