package me.mrarcane.core.listeners;

import me.mrarcane.core.Main;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.Sound;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.EnderDragon;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.entity.EntityDeathEvent;
import org.bukkit.event.entity.PlayerDeathEvent;
import org.bukkit.event.player.PlayerRespawnEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.scoreboard.Score;
import org.bukkit.scoreboard.Scoreboard;
import org.bukkit.scoreboard.ScoreboardManager;
import ru.tehkode.permissions.PermissionUser;
import ru.tehkode.permissions.bukkit.PermissionsEx;

import java.util.Random;

import static me.mrarcane.core.utils.ChatUtils.sendAlert;
import static me.mrarcane.core.utils.ChatUtils.sendChat;

/**
 * File generated by: MrArcane
 * 2/8/2018
 **/
public class DeathListener implements Listener {

    @EventHandler
    public static void onPlayerDeath(PlayerDeathEvent e) {
        FileConfiguration cfg = Main.getInstance().getConfig();
        Player p = e.getEntity();
        int x = p.getLocation().getBlockX();
        int y = p.getLocation().getBlockY();
        int z = p.getLocation().getBlockZ();
        ScoreboardManager sm = Bukkit.getScoreboardManager();
        Scoreboard sb = sm.getMainScoreboard();
        Score deaths = sb.getObjective("Deaths").getScore(p.getDisplayName());
        int d = deaths.getScore() + 1;
        Bukkit.getScheduler().runTask(Main.getInstance(), () -> {
            if (p.getName().equalsIgnoreCase("cowman10123")) {
                e.setDeathMessage(e.getDeathMessage());
                sendAlert(String.format("&6That's one more for the pile. Cowman is now at &7%s &6deaths", d));
                for (Player po : Bukkit.getOnlinePlayers()) {
                    po.playSound(po.getLocation(), Sound.ENTITY_COW_DEATH, 10, 1);
                }
            }
        });
        if (Main.getInstance().getConfig().getConfigurationSection("General").getBoolean("Perks")) {
            sendChat(p, "&eDeath location:");
            sendChat(p, String.format("&eX: &7%s &eY: &7%s &eZ: &7%s", x, y, z));
        }
    }
    @EventHandler
    public static void onRespawn(PlayerRespawnEvent e) {
        FileConfiguration cfg = Main.getInstance().getConfig();
        ConfigurationSection gs = cfg.getConfigurationSection("Spawn.Guest spawn");
        Player p = e.getPlayer();
        PermissionUser pu = PermissionsEx.getUser(p);
        if (gs != null && pu.inGroup(gs.getString("Group"))) {
            e.setRespawnLocation(new Location(Bukkit.getWorld(gs.getString("w")), gs.getDouble("x"), gs.getDouble("y"), gs.getDouble("z")));
            return;
        }
        if (!e.isBedSpawn()) {
            ConfigurationSection s = cfg.getConfigurationSection("Spawn");
            if (cfg.getConfigurationSection("Spawn") != null) {
                e.setRespawnLocation(new Location(Bukkit.getWorld(s.getString("w")), s.getDouble("x"), s.getDouble("y"), s.getDouble("z")));
            }
        }
    }
    @EventHandler
    public static void onMobDeath(EntityDeathEvent event) {
        Random r = new Random();
        Random r2 = new Random();
        Random r3 = new Random();
        Player p = event.getEntity().getKiller();
        int e = r.nextInt(4);
        int s = r2.nextInt(100);
        int d = r3.nextInt(500);
        if (event.getEntity() instanceof EnderDragon) {
            if (e == 2) {
               p.getInventory().addItem(new ItemStack(Material.ELYTRA));
                sendChat(p, "&eAn elytra has appeared in your inventory.");
            }
            if (s == 27) {
                p.getInventory().addItem(new ItemStack(Material.SHULKER_SHELL, 2));
                sendChat(p, "&eShulker shells have appeared in your inventory.");
            }
            if (d == 395) {
                p.getInventory().addItem(new ItemStack(Material.DRAGON_EGG));
                sendChat(p, "&eA dragon egg has appeared in your inventory.");
            }
        }
    }
}
