package me.mrarcane.core.listeners;

import me.mrarcane.core.utils.PlayerUtils;
import org.bukkit.GameMode;
import org.bukkit.Location;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerQuitEvent;

import static me.mrarcane.core.commands.SpectateCommand.l;
import static me.mrarcane.core.utils.PlayerUtils.adminMode;
import static me.mrarcane.core.utils.PlayerUtils.inv;

/**
 * File generated by: MrArcane
 * 1/6/2018
 **/
public class QuitListener implements Listener {

    @EventHandler
    private void onQuit(final PlayerQuitEvent e) {
        Player p = e.getPlayer();
        Location loc = p.getLocation();
        PlayerUtils pd = new PlayerUtils(p.getUniqueId().toString());
        ConfigurationSection pFile = pd.getConfigurationSection("Player");
        pFile.set("Time", System.currentTimeMillis());
        pFile.set("x", loc.getBlockX());
        pFile.set("y", loc.getBlockY());
        pFile.set("z", loc.getBlockZ());
        pFile.set("world", loc.getWorld().getName());
        pd.save();
        if (inv.containsKey(p)) {
            adminMode(p);
        }
        if (l.containsKey(p)) {
            p.teleport(l.get(p));
            p.setGameMode(GameMode.SURVIVAL);
            l.remove(p);
        }
    }
}
