package me.mrarcane.core.listeners;

import com.vexsoftware.votifier.model.Vote;
import com.vexsoftware.votifier.model.VotifierEvent;
import me.mrarcane.core.Main;
import org.bukkit.Bukkit;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

import java.util.HashMap;
import java.util.List;

/**
 * File generated by: MrArcane
 * 12/27/2017
 **/
public class VoteListener implements Listener {
    public static HashMap<Player, Integer> v = new HashMap<>();
    @EventHandler
    public static void onVote(final VotifierEvent e) {
        Vote vote = e.getVote();
        ConfigurationSection cfg = Main.getInstance().getConfig();
        List<String> cList = cfg.getStringList("Vote.Commands");
        Player p = Bukkit.getPlayer(vote.getUsername());
        if (p == null) {
            return;
        }
        for (String cmd : cList) {
            Bukkit.dispatchCommand(Bukkit.getConsoleSender(), cmd.replace("{player}", p.getDisplayName()));
        }
    }
}
