package me.mrarcane.core.utils;

import me.mrarcane.core.Main;
import org.bukkit.Bukkit;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.plugin.Plugin;
import org.bukkit.scheduler.BukkitTask;

import java.util.List;
import java.util.Random;

import static me.mrarcane.core.Main.announcer;
import static me.mrarcane.core.utils.ChatUtils.log;
import static me.mrarcane.core.utils.ChatUtils.sendAlert;

/**
 * File generated by: MrArcane
 * 1/9/2018
 **/
public class BroadcastUtils {

    public static BukkitTask broadcast(Plugin plugin) {
        ConfigurationSection cfg = Main.getInstance().getConfig();
        List<String> msgs = cfg.getStringList("Broadcast.Messages");
        long interval = cfg.getLong("Broadcast.Interval");
        long time = interval * 1200; //This allows it to go through every 1 minute.
        Random r = new Random();
        return Bukkit.getScheduler().runTaskTimerAsynchronously(plugin, () -> {
            if (Bukkit.getOnlinePlayers().size() < 1) { //Be smart and shut her down :)
                log("There are no players online, shutting down broadcaster to reduce console spam.");
                announcer.cancel();
                return;
            }
            if (msgs.size() < 1) {
                announcer.cancel();
                return;
            }
            sendAlert(Main.core + " " + msgs.get(r.nextInt(msgs.size())));
        }, time, time);
    }
    public static void restart(Plugin plugin) {
        announcer.cancel();
        announcer = broadcast(plugin);
    }
}