package me.mrarcane.core.utils;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.command.CommandSender;

/**
 * File generated by: MrArcane
 * 11/7/2017
 **/
public class ChatUtils {

    public static String color(String in) {
        return ChatColor.translateAlternateColorCodes('&', in);
    }
    public static void sendChat(CommandSender p, String msg) {
        p.sendMessage(color(msg));
    }
    public static void sendAlert(String msg) {
        Bukkit.getServer().broadcastMessage(color(msg));
    }
    public static void log(String msg) {
        Bukkit.getConsoleSender().sendMessage(color("[Core] " + msg));
    }
}
