package me.mrarcane.core.utils;

import me.mrarcane.core.Main;
import org.bukkit.Bukkit;
import org.bukkit.plugin.Plugin;
import org.bukkit.scheduler.BukkitTask;

import java.util.HashMap;
import java.util.Map;

import static me.mrarcane.core.Main.failedVote;
import static me.mrarcane.core.Main.voting;
import static me.mrarcane.core.commands.DayCommand.*;
import static me.mrarcane.core.utils.ChatUtils.sendAlert;

/**
 * File generated by: MrArcane
 * 1/21/2018
 **/
public class DaySwitchUtils {

    public static Map<Plugin, Boolean> fail = new HashMap<>();
    private static int t = Main.getInstance().getConfig().getConfigurationSection("Day switch").getInt("Time");
    private static Map<Plugin, Integer> time = new HashMap<>();
    private static BukkitTask failed(Plugin plugin) {
        return Bukkit.getScheduler().runTaskTimerAsynchronously(plugin, () -> {
            if (plugin.getServer().getWorld("world").getTime() >= 12000 && plugin.getServer().getWorld("world").getTime() <=13000) {
                resetFailedVote();
            }
        }, 0L, 20L);
    }
    private static BukkitTask vote(Plugin plugin) {
        time.put(plugin, t);
        return Bukkit.getScheduler().runTaskTimer(plugin, () -> {
            t--;
            time.put(plugin, t);
            if (time.get(plugin) == 5) {
                sendAlert("&aDay switch ending in 5 seconds!");
                return;
            }
            if (Integer.parseInt(String.valueOf(time.get(plugin))) == 0) {
                if (yes == no) {
                    resetVote();
                    sendAlert("&eTied, time hasn't been affected.");
                    fail.put(plugin, true);
                    startFailedVote();
                    return;
                }
                if (no > yes) {
                    resetVote();
                    sendAlert("&4Failed, time hasn't been affected.");
                    fail.put(plugin, true);
                    startFailedVote();
                    return;
                }
                if (yes > no) {
                    resetVote();
                    plugin.getServer().getWorld("world").setTime(0);
                    plugin.getServer().getWorld("world").setStorm(false);
                    sendAlert("&aSuccessful, time has been switched to day.");
                }
            }
        }, t, t);
    }
    private static void startFailedVote() {
        failedVote = failed(Main.getInstance());
    }
    private static void resetFailedVote() {
        failedVote.cancel();
        fail.clear();
        sendAlert("&aYou can now vote for day again.");
    }
    public static void startVote() {
        voting = vote(Main.getInstance());
    }
    public static void resetVote() {
        Main.voting.cancel();
        time.clear();
        user.clear();
        sMap.put(Main.getInstance(), false);
        yes = 0;
        no = 0;
        t = Main.getInstance().getConfig().getInt("Day switch.Time");
        Main.getInstance().saveConfig();
    }
}
