package me.mrarcane.core;

import me.mrarcane.core.commands.*;
import me.mrarcane.core.listeners.*;
import me.mrarcane.core.utils.BroadcastUtils;
import me.mrarcane.core.utils.ChatUtils;
import me.mrarcane.core.utils.PlayerUtils;
import org.bukkit.Bukkit;
import org.bukkit.GameMode;
import org.bukkit.command.CommandExecutor;
import org.bukkit.entity.Player;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.scheduler.BukkitTask;

import static me.mrarcane.core.commands.DayCommand.sMap;
import static me.mrarcane.core.commands.SpectateCommand.l;
import static me.mrarcane.core.utils.PlayerUtils.adminMode;

/**
 * File generated by: MrArcane
 * 11/6/2017
 **/
public class Main extends JavaPlugin {

   private static Main instance;
   public static BukkitTask announcer;
   public static BukkitTask voting;
   public static BukkitTask failedVote;
   public static String core = "&7[&aCo&2re&7] ";
    private static void cmd(String cmd, CommandExecutor executor) {
        getInstance().getServer().getPluginCommand(cmd).setExecutor(executor);
    }
    private static void event(Listener listener) {
        getInstance().getServer().getPluginManager().registerEvents(listener, getInstance());
    }
    public static Main getInstance() {
        return instance;
    }
    public void onEnable() {
        instance = this;
        this.saveDefaultConfig();
        //Commands
        cmd("core", new CoreCommand());
        cmd("broadcast", new BroadcastCommand());
        cmd("links", new LinksCommand());
        cmd("vote", new VoteCommand());
        cmd("autobroadcast", new AutoBroadcastCommand());
        cmd("spectate", new SpectateCommand());
        cmd("teleport", new TeleportCommand());
        cmd("Mail", new MailCommand());
        cmd("seen", new SeenCommand());
        cmd("rules", new RulesCommand());
        cmd("day", new DayCommand());
        cmd("perks", new PerksCommand());
        cmd("hat", new HatCommand());
        cmd("away", new AwayCommand());
        cmd("sendchat", new SendChatCommand());
        cmd("setspawn", new SetSpawnCommand());
        cmd("setguestspawn", new SetGuestSpawnCommand());
        cmd("staff", new StaffCommand());
        cmd("dilly", new DillyCommand());
        cmd("adminmode", new AdminModeCommand());
        ChatUtils.log(String.format("%s commands loaded.", this.getDescription().getCommands().size()));
        //Events
        event(new ChatListener());
        event(new JoinListener());
        event(new MoveListener());
        event(new QuitListener());
        event(new VoteListener());
        event(new DeathListener());
        event(new BedListener());
        event(new AwayListener());
        //Other
        announcer = BroadcastUtils.broadcast(this);
        sMap.put(Main.getInstance(), false);
    }
    public void onDisable() {
        for (Player p : Bukkit.getOnlinePlayers()) {
            if (PlayerUtils.inv.containsKey(p)) {
                adminMode(p);

            }
            if (l.containsKey(p)) {
                p.teleport(l.get(p));
                p.setGameMode(GameMode.SURVIVAL);
                l.remove(p);
            }
        }
    }
}
